theme: jekyll-theme-merlot
title: Tuan Nguyen
description: Read more, write better
show_downloads: true
picosix:
  blog_url: https://nodeplusplus.com/
  linkedin_url: https://www.linkedin.com/in/tuannguyen1993/
